### PR TITLE
UDT decomposition from StableDQMC

### PR DESCRIPTION
**Pull request by ffreyer**
A side remark motivated by your last commit (fix QR):
>It would be great to use the linalg stuff from StableDQMC.jl here (in MonteCarlo.jl). In particular I'm thinking of the UDT `<: Factorization` type. However, maybe we don't want to add another dependency? Perhaps we should copy paste stuff over?

_Originally posted by @crstnbr in https://github.com/crstnbr/MonteCarlo.jl/pull/2#issuecomment-504359128_

I copied over the contents of `qr_udt.jl` from [StableDQMC](
https://github.com/crstnbr/StableDQMC.jl) to `linalg.jl`. The old `linalg.jl` has been moved to tests and is still used by `testfunctions.jl`. `calculate_greens` now uses `udt_inv_one_plus`, which freed up some temporary matrices (`s.u`, `s.d`, `s.t` are out, `s.tmp` in)

TODO

- [x] cleanup linalg (remove loh functions, ...?)

### CODE REVIEW

**Comment by carstenbauer** [comment]
Perhaps it's better to add StableDQMC as a dependency first, such that we can optimize and sem-version the methods in it independently of MonteCarlo.jl. After my recent refactor, it is a very lightweight dependency (check it's README.md). What do you think?

Also, we could remove the *_loh* functions, since they are not necessary for DQMC itself but only for calculating the TDGF. If we have StableDQMC as a dependency, we don't have to care.

**Comment by ffreyer** [comment]
I did some performance comparisons between DQMC.jl (private) and StableDQMC.jl. 
* `decompose_udt` and `udt` are equally performant for 4x4, 100x100 and 1000x1000 matrices
* `decompose_udt!` and `udt!` are equally performant for 4x4, 100x100 and 1000x1000 matrices (even though `udt!` creates a vector `D` while `decompose_udt!` does not)
* in-place `udt!` (i.e. w/o creating D) is equally performant as the normal `udt!` for 4x4, 100x100, 1000x1000 matrices
* `inv_one_plus_two_udts!` and `udt_inv_one_plus` are equally performant for 4x4 and 100x100 matrices

On a side note - StableDQMC's `udt_inv_one_plus` actually has one more allocation (and slightly more memory usage) with `internaluse = true`.

**Comment by carstenbauer** [comment]
> I did some performance comparisons between DQMC.jl (private) and StableDQMC.jl.

Great. Results look good 

> * `inv_one_plus_two_udts!` and `udt_inv_one_plus` are equally performant for 4x4 and 100x100 matrices

What about 1000x1000 here?

> On a side note - StableDQMC's `udt_inv_one_plus` actually has one more allocation (and slightly more memory usage) with `internaluse = true`.

That's not expected. For Monte Carlo this shouldn't matter though, since one would use the in-place version (with a bang) anyways.

Test failures seem unrelated? Can this be merged?

**Comment by ffreyer** [comment]
> > I did some performance comparisons between DQMC.jl (private) and StableDQMC.jl.
> 
> Great. Results look good
> 
> > * `inv_one_plus_two_udts!` and `udt_inv_one_plus` are equally performant for 4x4 and 100x100 matrices
> 
> What about 1000x1000 here?

I didn't check it. Also seems about the same; maybe StableDQMC is slightly faster. But the sample size is rather low.

> > On a side note - StableDQMC's `udt_inv_one_plus` actually has one more allocation (and slightly more memory usage) with `internaluse = true`.
> 
> That's not expected. For Monte Carlo this shouldn't matter though, since one would use the in-place version (with a bang) anyways.
> 
> Test failures seem unrelated? Can this be merged?

The test failures should be fixed in #7. Yes, this can be merged.

**Pull request merged**
