### PR TITLE
V1.1 patches

### PR DESCRIPTION
**Pull request by ffreyer**
`run!(dqmc)` now works again with julia 1.1 but not julia 1.0

### CODE REVIEW

**Comment by carstenbauer** [comment]
A side remark motivated by your last commit (fix QR): It would be great to use the linalg stuff from StableDQMC.jl here (in MonteCarlo.jl). In particular I'm thinking of the UDT `<: Factorization` type. However, maybe we don't want to add another dependency? Perhaps we should copy past stuff over?

**Comment by ffreyer** [comment]
I'm leaning towards copying the relevant parts. We don't need the paper, notebooks or svd decompositions (and dependencies) here.

**Comment by ffreyer** [comment]
I think the deprecations are now all fixed. `test` runs without errors on v1.0 and v1.1, `run!(dqmc)` works for both and `example/Ising2d.jl` starts up for both versions.

What's left to do is:
- [x] Check if the documentation needs updates (specifically regarding `example/Ising2D.jl`)
- [x] Fix 3 failing accuracy tests

**Comment by ffreyer** [comment]
I think the failure in the Ising test is the test being wrong. `beta = 0.35` (T ~ 2.86) is of the paramagnetic regime, so we expect a large variance/standard deviation. The test suggests `0.398 +- 0.014`, the simulation `0.398 +- 0.241`.

**Comment by carstenbauer** [comment]
> I think the failure in the Ising test is the test being wrong. `beta = 0.35` (T ~ 2.86) is of the paramagnetic regime, so we expect a large variance/standard deviation. The test suggests `0.398 +- 0.014`, the simulation `0.398 +- 0.241`.

Note that when this test was written `std(o::Observable)` was calculating the standard error of the mean and not the standard deviation. At some point I changed that in MonteCarloObservable.jl and introduced `error` for this. So first thing I'd try is replace the `std` by `error` (or fix MonteCarloObservable to an older version).

Having said that, note that this test isn't rigorous at all. It is only a "self-consistent" check for wether we broke something relative to a previous state of the package. So having it error doesn't mean per se that something is wrong/broken.

**Comment by carstenbauer** [comment]
However, the other two tests related to the Green's function calculation must be taken seriously.

**Comment by carstenbauer** [comment]
I took the liberty to fix the travis config file such that travis runs again (still fails due to tests mentioned above). I left the (probably unnecessary?) python dependencies for now.

**Comment by ffreyer** [comment]
> At some point I changed that in MonteCarloObservable.jl and introduced `error` for this. So first thing I'd try is replace the `std` by `error` (or fix MonteCarloObservable to an older version).

`error(m)` returns `0.012` instead of `0.014`.

**Comment by carstenbauer** [comment]
> `error(m)` returns `0.012` instead of `0.014`.

This wouldn't worry me (i.e. just adjust the test). Probably we use a slightly different way to calculate the standard error in MCO now.

**Comment by ffreyer** [comment]
Tests should now be fixed. If no more issues pop up this can be merged.

**Comment by ffreyer** [comment]
There is still

```
┌ Warning: Package MonteCarlo does not have Printf in its dependencies:
│ - If you have MonteCarlo checked out for development and have
│   added Printf as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with MonteCarlo
└ Loading Printf into MonteCarlo from project dependency, future warnings for MonteCarlo are suppressed.
```

which I don't get since `Printf` is in stdlib.
And I have no idea how to work with appveyor.

**Comment by ffreyer** [comment]
I used the Appveyor script suggested by https://github.com/JuliaCI/Appveyor.jl . If you had anything fancy set up it is no longer there.

I also added stdlib packages to the Project.toml. With that this should be ready to be merged.

**Comment by carstenbauer** [comment]
I'll merge this to have things (at least) running again.

However, many things must be revisited, for example the handling of keyword args as `Dict`s (probably named tuples here?).

Thanks for the changes!

**Pull request merged**
